### PR TITLE
pup: support for advanced triggers

### LINKED ISSUE #1786: triggers.pup not supporting the equal sign nor multiple conditions (standalone)
**Describe the bug**
While trying to understand why some pup videos don't launch, I made an interesting discovery:
Let's take "back to the future" https://vpuniverse.com/files/file/11060-back-to-the-future-mod-by-nitronimbus-cw-pup-pack/page/5/?tab=comments (for a more convenient download go to https://mega.nz/file/zmpFDJoC#yrdQhrt5Td38Y7VRF3ZWsVBP61KBp7gj1gyGaesy6oE as indicated in the comments).
The ball drain didn't trigger anything:
28,1,Drain,W10=1,2,Drain_5,,100,9,,,8,,0
But if I replace by:
28,1,Drain,W10,2,Drain_5,,100,9,,,8,,0
then it works fine.
So, I'm pretty sure that when there's a equal, it's not triggered.

**Versions & Settings**
 - VPinballX_GL-10.8.1-2362-ad4cd07-Release-linux-x64

### PR DESCRIPTION
**Pull request by francisdb**
eg: `L23,W38=1,W39=1,W40=0`

this fixes #1786

* removed the trigger filters where only 1 values were passed
* keeps track of latest values
* parses all pup triggers
* makes sure all values match

The only thing I am not 100% sure about is if for example in above case `W40` goes to `0` and the rest already matched if we should also cause an event? Currently we see the first one as the main trigger so only a change to that one while the rest already matches can initiate an event.

### CODE REVIEW

File: standalone/inc/pup/PUPManager.cpp [hunk 1]
```diff
@@ -230,14 +230,10 @@ TTF_Font* PUPManager::GetFont(const string& szFont)
 
 void PUPManager::QueueTriggerData(PUPTriggerData data)
 {
-   if (data.value == 0)
-      return;
-
    {
```
Comment (jsm174) [inline standalone/inc/pup/PUPManager.cpp:233]: I remember specifically adding this. I feel like it was related to dof or something, but this would get hammered.

File: standalone/inc/pup/PUPScreen.cpp [hunk 2]
```diff
@@ -459,15 +459,30 @@ void PUPScreen::QueueBG(int mode)
 
 void PUPScreen::QueueTrigger(char type, int number, int value)
 {
-   if (value == 0)
-      return;
+   // we store the whole state to be able to mach later
+   const std::string name = std::string(1, type) + std::to_string(number);
+   m_triggersState[name] = value;
```
Comment (jsm174) [inline standalone/inc/pup/PUPScreen.cpp:465]: core/stdafx.h namespaces std::string and std::vector, so you don't need std:: anywhere you use these.

File: standalone/inc/pup/PUPScreen.cpp [hunk 3]
```diff
@@ -459,15 +459,30 @@ void PUPScreen::QueueBG(int mode)
...
    vector<PUPTrigger*>* pTriggers = GetTriggers(type + std::to_string(number));
    if (!pTriggers)
       return;
 
    for (PUPTrigger* pTrigger : *pTriggers) {
-      PUPTriggerRequest* pRequest = new PUPTriggerRequest();
+      if (!pTrigger->IsActive())
+         continue;
+
+      for (const auto& [m_sName, value] : pTrigger->GetTriggers()) {
```
Comment (jsm174) [inline standalone/inc/pup/PUPScreen.cpp:475]: `m_` represents a member class variable. use name name or something else.

File: standalone/inc/pup/PUPScreen.cpp [hunk 4]
```diff
@@ -459,15 +459,30 @@ void PUPScreen::QueueBG(int mode)
...
+         auto currentValue = m_triggersState.find(m_sName);
+         if (currentValue == m_triggersState.end()) {
```
Comment (jsm174) [inline standalone/inc/pup/PUPScreen.cpp:477]: for formatting consistency, single line if's you don't need braces unless you have another large if, for, or are using PLOG statements. also, it looks like you could have just OR'd it

```
if (currentValue == m_triggersState.end() || currentValue->second != value)
   return;
```

File: standalone/inc/pup/PUPScreen.h [hunk 5]
```diff
@@ -173,4 +173,5 @@ class PUPScreen
    bool m_isRunning;
    std::thread m_thread;
    std::mutex m_renderMutex;
+   std::unordered_map<std::string, int> m_triggersState;
```
Comment (jsm174) [inline standalone/inc/pup/PUPScreen.h:176]: should we be using these other maps?

File: standalone/inc/pup/PUPTrigger.cpp [hunk 6]
```diff
@@ -56,11 +56,11 @@ const char* PUP_TRIGGER_PLAY_ACTION_TO_STRING(PUP_TRIGGER_PLAY_ACTION value)
      D = PupCap DMD Match
 */
 
-PUPTrigger::PUPTrigger(bool active, const string& szDescript, const string& szTrigger, PUPScreen* pScreen, PUPPlaylist* pPlaylist, const string& szPlayFile, float volume, int priority, int length, int counter, int restSeconds, PUP_TRIGGER_PLAY_ACTION playAction)
+PUPTrigger::PUPTrigger(bool active, const string& szDescript, const std::vector<StateTrigger>& vTriggers, PUPScreen* pScreen, PUPPlaylist* pPlaylist, const string& szPlayFile, float volume, int priority, int length, int counter, int restSeconds, PUP_TRIGGER_PLAY_ACTION playAction)
 {
    m_active = active;
    m_szDescript = szDescript;
-   m_szTrigger = szTrigger;
+   m_vTriggers = vTriggers;
```
Comment (jsm174) [inline standalone/inc/pup/PUPTrigger.cpp:63]: we don't usually use v to represent vectors. just the name.

File: standalone/inc/pup/PUPTrigger.cpp [hunk 7]
```diff
@@ -159,6 +159,46 @@ PUPTrigger* PUPTrigger::CreateFromCSV(PUPScreen* pScreen, string line)
    );
 }
 
+std::vector<StateTrigger> PUPTrigger::ParseTriggers(const std::string& triggerString) {
```
Comment (jsm174) [inline standalone/inc/pup/PUPTrigger.cpp:162]: same std::vector -> vector comment from earlier.

File: standalone/inc/pup/PUPTrigger.cpp [hunk 8]
```diff
@@ -159,6 +159,46 @@ PUPTrigger* PUPTrigger::CreateFromCSV(PUPScreen* pScreen, string line)
...
+            }
+            trigger.value = std::stoi(token.substr(equalPos + 1));
+         } else {
+            // Parse triggers without state (e.g., "S10")
+            trigger.m_sName = token;
+            trigger.value = 1;
+         }
+
+         vTriggers.push_back(std::move(trigger));
+      } catch (const std::invalid_argument& e) {
```
Comment (jsm174) [inline standalone/inc/pup/PUPTrigger.cpp:192]: catches on next line for consistency

File: standalone/inc/pup/PUPTrigger.h [hunk 9]
```diff
@@ -19,17 +19,39 @@ typedef enum
    PUP_TRIGGER_PLAY_ACTION_CUSTOM_FUNC     // Call a custom function
 } PUP_TRIGGER_PLAY_ACTION;
 
+struct StateTrigger{
```
Comment (jsm174) [inline standalone/inc/pup/PUPTrigger.h:22]: we tried to stick with prefixing structs with PUP for example, also space after Trigger {

File: standalone/inc/pup/PUPTrigger.h [hunk 10]
```diff
@@ -19,17 +19,39 @@ typedef enum
...
 {
 public:
-   ~PUPTrigger() {}
-
+   ~PUPTrigger() { }
    static PUPTrigger* CreateFromCSV(PUPScreen* pScreen, string line);
    bool IsActive() const { return m_active; }
    const string& GetDescription() const { return m_szDescript; }
-   const string& GetTrigger() const { return m_szTrigger; }
+   /**
```
Comment (jsm174) [inline standalone/inc/pup/PUPTrigger.h:38]: Any class methods that have lots of code, I'd rather have in the cpp instead of the h file. Especially since you have lots of comments about the purpose of the function.

if you wanted to stay in, you could do something like:

```
const string& GetMainTriggerName() const { return !m_triggers.empty() ? m_triggers.front().m_sName : NO_TRIGGER; }
```

**Review by jsm174 — CHANGES_REQUESTED** [review]

File: standalone/inc/pup/PUPManager.cpp (hunk 1 above)
Comment (francisdb) [reply standalone/inc/pup/PUPManager.cpp:233]: Pup triggers can trigger when a value goes to 0. Not sure why dof is related as this is in the pup code?

Comment (jsm174) [reply standalone/inc/pup/PUPManager.cpp:233]: As I said, it was a long time since I wrote that, but I do remember specifically putting that in for a reason.  We'll see what happens.

File: standalone/inc/pup/PUPScreen.cpp (hunk 4 above)
Comment (francisdb) [reply standalone/inc/pup/PUPScreen.cpp]: Can such things be put in the clang-format file?

**Comment by francisdb** [comment]
I will squash once this gets through the review

File: standalone/inc/pup/PUPTrigger.cpp [hunk 11]
```diff
@@ -76,7 +76,8 @@ PUPTrigger::PUPTrigger(bool active, const string& szDescript, const string& szTr
 PUPTrigger* PUPTrigger::CreateFromCSV(PUPScreen* pScreen, string line)
 {
    vector<string> parts = parse_csv_line(line);
-   if (parts.size() != 14) {
+   if (parts.size() != 14)
```
Comment (jsm174) [inline standalone/inc/pup/PUPTrigger.cpp:79]: I think the brace formatting got changed on this file. { after if's etc.

Comment (francisdb) [reply standalone/inc/pup/PUPTrigger.cpp:79]: Is there some kind of command I can run to validate formatting or even better reformat?

Comment (jsm174) [reply standalone/inc/pup/PUPTrigger.cpp:79]: unfortunately no, it's more just stick with the rest of the code base for consistency. sorry

File: .clang-format [hunk 12]
```diff
@@ -3,7 +3,11 @@
 BasedOnStyle: WebKit
 AccessModifierOffset: -3
 AllowShortCaseLabelsOnASingleLine: true
-BreakBeforeBraces: Allman
+BreakBeforeBraces: Custom
+BraceWrapping:
+  AfterControlStatement: false
```
Comment (vbousquet) [inline .clang-format:8]: Not sure why you want to change this. The clang-format is not that old and the codebase is being normalized slowly as the code is refactored/updated (we decided against a global format update). Whanging the clang-format now would mean that a large part of the codebase would have to be updated and that it will take longer to get consistent formatting in the project.

Comment (francisdb) [reply .clang-format:8]: Because @jsm174 told me the rules were different.

Comment (jsm174) [reply .clang-format:8]: There are no official rules. I was just asking you to keep the code similar to what we had in every other PUP file. 
I don't have my editor try to automatically format my code.. That stuff never works 100%.

Comment (vbousquet) [reply .clang-format:8]: No problem, just please, don't modify the clang-format file as it will makes things a bit more difficult in the src folder where I have autoformatting enabled in MSVC

Comment (francisdb) [reply .clang-format]: reverted

**Comment by francisdb** [comment]
> I have been facing the same difficulties on the pup plugin I'm implementing at the moment. In the end, I had to entirely remove triggering through a string (`QueueTrigger`) since it would fail to evaluate correctly if faced to more complex triggers that would not match the string lookup. If you want, you can have a look at the branch where things are being prepared: https://github.com/vbousquet/vpinball/tree/pup_plugin

So I guess any further work for #1786, #2366 or #2344 better be postponed until that plugin is ready?

**Comment by jsm174** [comment]
@vbousquet - I merged this, but I talked to @nailbuster to better understand how these work, and was going to start working on a revision. I had an idea on what I wanted to do, but I'll take a look at your work.

**Comment by vbousquet** [comment]
> > I have been facing the same difficulties on the pup plugin I'm implementing at the moment. In the end, I had to entirely remove triggering through a string (`QueueTrigger`) since it would fail to evaluate correctly if faced to more complex triggers that would not match the string lookup. If you want, you can have a look at the branch where things are being prepared: https://github.com/vbousquet/vpinball/tree/pup_plugin
> 
> So I guess any further work for #1786, #2366 or #2344 better be postponed until that plugin is ready?

I based my work on the standalone PUP renderer. So whatever you do will help. The plugin system is a long shot and will need time to be stable, so pushing updates to regular standalone allows to improve things, have more regular mobile release, and is also usefull for the plugin branch.
